---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: "Allow"
          Action:
          - "sts:AssumeRole"
          Principal:
            Service:
            - "lambda.amazonaws.com"
        Version: "2012-10-17"
      ManagedPolicyArns:
      - Fn::Join:
        - ""
        - - "arn:"
          - Ref: "AWS::Partition"
          - ":iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
      Path: "/"
      Policies:
      - PolicyDocument:
          Statement:
          - Effect: "Allow"
            Action:
            - "logs:CreateLogStream"
            Resource:
            - Fn::Join:
              - ""
              - - "arn:"
                - Ref: "AWS::Partition"
                - ":logs:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":log-group:/aws/lambda/htt4k-aws-demo-demo-definition:*"
          - Effect: "Allow"
            Action:
            - "logs:PutLogEvents"
            Resource:
            - Fn::Join:
              - ""
              - - "arn:"
                - Ref: "AWS::Partition"
                - ":logs:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":log-group:/aws/lambda/htt4k-aws-demo-demo-definition:*"
                - ":*"
          Version: "2012-10-17"
        PolicyName: "demo-htt4k-aws-demo-lambda"
  LogGroupDemohelloworld:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: "/aws/lambda/htt4k-aws-demo-demo-demo-hello-world"
  FunctionDemohelloworld:
    Type: "AWS::Lambda::Function"
    DependsOn:
    - "LogGroupDemohelloworld"
    - "Role"
    Properties:
      Code:
        S3Bucket: "lambda-cf-bucket2"
        S3Key: "htt4k-aws-demo/4163315315506-2019-11-21-22:04:25/http4k-aws-demo-uber.jar"
      Handler: "io.hexlabs.HelloWorldHandler"
      Role:
        Fn::GetAtt:
        - "Role"
        - "Arn"
      Runtime: "java8"
      MemorySize: 512
      Timeout: 30
  RestApi:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: "demo-htt4k-aws-demo"
  ApiGatewayResourcehello:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId:
        Fn::GetAtt:
        - "RestApi"
        - "RootResourceId"
      PathPart: "hello"
      RestApiId:
        Ref: "RestApi"
  MethodhelloGET:
    Type: "AWS::ApiGateway::Method"
    Properties:
      HttpMethod: "GET"
      ResourceId:
        Ref: "ApiGatewayResourcehello"
      RestApiId:
        Ref: "RestApi"
      ApiKeyRequired: false
      AuthorizationType: "None"
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri:
          Fn::Join:
          - ""
          - - "arn:"
            - Ref: "AWS::Partition"
            - ":apigateway:"
            - Ref: "AWS::Region"
            - ":lambda:path/2015-03-31/functions/"
            - Fn::GetAtt:
              - "FunctionDemohelloworld"
              - "Arn"
            - "/invocations"
      MethodResponses: []
      RequestParameters: {}
  ApiDeploymentcab0d25394404197af40f7f0f28a35c2:
    Type: "AWS::ApiGateway::Deployment"
    DependsOn:
    - "MethodhelloGET"
    Properties:
      RestApiId:
        Ref: "RestApi"
      StageName: "demo"
  Permission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::GetAtt:
        - "FunctionDemohelloworld"
        - "Arn"
      Principal:
        Fn::Join:
        - ""
        - - "apigateway."
          - Ref: "AWS::URLSuffix"
      SourceArn:
        Fn::Join:
        - ""
        - - "arn:"
          - Ref: "AWS::Partition"
          - ":execute-api:"
          - Ref: "AWS::Region"
          - ":"
          - Ref: "AWS::AccountId"
          - ":"
          - Ref: "RestApi"
          - "/*/*"
  LogGroupDemohttpk:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: "/aws/lambda/htt4k-aws-demo-demo-demo-http4k"
  FunctionDemohttpk:
    Type: "AWS::Lambda::Function"
    DependsOn:
    - "LogGroupDemohttpk"
    - "Role"
    Properties:
      Code:
        S3Bucket: "lambda-cf-bucket2"
        S3Key: "htt4k-aws-demo/4163315315506-2019-11-21-22:04:25/http4k-aws-demo-uber.jar"
      Handler: "org.http4k.serverless.lambda.LambdaFunction::handle"
      Role:
        Fn::GetAtt:
        - "Role"
        - "Arn"
      Runtime: "java8"
      Environment:
        Variables:
          HTTP4K_BOOTSTRAP_CLASS: "io.hexlabs.vehicle.inventory.InventoryHandlerLambdaFunction"
      MemorySize: 512
      Timeout: 30
  RestApi2:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: "demo-htt4k-aws-demo"
  ApiGatewayResourceinventory:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId:
        Fn::GetAtt:
        - "RestApi2"
        - "RootResourceId"
      PathPart: "inventory"
      RestApiId:
        Ref: "RestApi2"
  ApiGatewayResourceinventorycars:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId:
        Ref: "ApiGatewayResourceinventory"
      PathPart: "cars"
      RestApiId:
        Ref: "RestApi2"
  MethodinventorycarsGET:
    Type: "AWS::ApiGateway::Method"
    Properties:
      HttpMethod: "GET"
      ResourceId:
        Ref: "ApiGatewayResourceinventorycars"
      RestApiId:
        Ref: "RestApi2"
      ApiKeyRequired: false
      AuthorizationType: "None"
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri:
          Fn::Join:
          - ""
          - - "arn:"
            - Ref: "AWS::Partition"
            - ":apigateway:"
            - Ref: "AWS::Region"
            - ":lambda:path/2015-03-31/functions/"
            - Fn::GetAtt:
              - "FunctionDemohttpk"
              - "Arn"
            - "/invocations"
      MethodResponses: []
      RequestParameters: {}
  MethodinventorycarsPOST:
    Type: "AWS::ApiGateway::Method"
    Properties:
      HttpMethod: "POST"
      ResourceId:
        Ref: "ApiGatewayResourceinventorycars"
      RestApiId:
        Ref: "RestApi2"
      ApiKeyRequired: false
      AuthorizationType: "None"
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri:
          Fn::Join:
          - ""
          - - "arn:"
            - Ref: "AWS::Partition"
            - ":apigateway:"
            - Ref: "AWS::Region"
            - ":lambda:path/2015-03-31/functions/"
            - Fn::GetAtt:
              - "FunctionDemohttpk"
              - "Arn"
            - "/invocations"
      MethodResponses: []
      RequestParameters: {}
  ApiGatewayResourceidVar:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId:
        Ref: "ApiGatewayResourceinventorycars"
      PathPart: "{id}"
      RestApiId:
        Ref: "RestApi2"
  MethodidVarGET:
    Type: "AWS::ApiGateway::Method"
    Properties:
      HttpMethod: "GET"
      ResourceId:
        Ref: "ApiGatewayResourceidVar"
      RestApiId:
        Ref: "RestApi2"
      ApiKeyRequired: false
      AuthorizationType: "None"
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri:
          Fn::Join:
          - ""
          - - "arn:"
            - Ref: "AWS::Partition"
            - ":apigateway:"
            - Ref: "AWS::Region"
            - ":lambda:path/2015-03-31/functions/"
            - Fn::GetAtt:
              - "FunctionDemohttpk"
              - "Arn"
            - "/invocations"
      MethodResponses: []
      RequestParameters: {}
  MethodidVarPUT:
    Type: "AWS::ApiGateway::Method"
    Properties:
      HttpMethod: "PUT"
      ResourceId:
        Ref: "ApiGatewayResourceidVar"
      RestApiId:
        Ref: "RestApi2"
      ApiKeyRequired: false
      AuthorizationType: "None"
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri:
          Fn::Join:
          - ""
          - - "arn:"
            - Ref: "AWS::Partition"
            - ":apigateway:"
            - Ref: "AWS::Region"
            - ":lambda:path/2015-03-31/functions/"
            - Fn::GetAtt:
              - "FunctionDemohttpk"
              - "Arn"
            - "/invocations"
      MethodResponses: []
      RequestParameters: {}
  MethodidVarDELETE:
    Type: "AWS::ApiGateway::Method"
    Properties:
      HttpMethod: "DELETE"
      ResourceId:
        Ref: "ApiGatewayResourceidVar"
      RestApiId:
        Ref: "RestApi2"
      ApiKeyRequired: false
      AuthorizationType: "None"
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri:
          Fn::Join:
          - ""
          - - "arn:"
            - Ref: "AWS::Partition"
            - ":apigateway:"
            - Ref: "AWS::Region"
            - ":lambda:path/2015-03-31/functions/"
            - Fn::GetAtt:
              - "FunctionDemohttpk"
              - "Arn"
            - "/invocations"
      MethodResponses: []
      RequestParameters: {}
  ApiDeployment6310837f1b6a45f1b937a94042229356:
    Type: "AWS::ApiGateway::Deployment"
    DependsOn:
    - "MethodinventorycarsGET"
    - "MethodinventorycarsPOST"
    - "MethodidVarGET"
    - "MethodidVarPUT"
    - "MethodidVarDELETE"
    Properties:
      RestApiId:
        Ref: "RestApi2"
      StageName: "demo"
  Permission2:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::GetAtt:
        - "FunctionDemohttpk"
        - "Arn"
      Principal:
        Fn::Join:
        - ""
        - - "apigateway."
          - Ref: "AWS::URLSuffix"
      SourceArn:
        Fn::Join:
        - ""
        - - "arn:"
          - Ref: "AWS::Partition"
          - ":execute-api:"
          - Ref: "AWS::Region"
          - ":"
          - Ref: "AWS::AccountId"
          - ":"
          - Ref: "RestApi2"
          - "/*/*"
Outputs:
  ServiceEndpoint:
    Value:
      Fn::Join:
      - ""
      - - "https://"
        - Ref: "RestApi2"
        - ".execute-api."
        - Ref: "AWS::Region"
        - "."
        - Ref: "AWS::URLSuffix"
        - "/demo"
    Description: "URL of the service"
